### ISSUE TITLE
missing few important details

### ISSUE THREAD

**Issue by tusharhqq** [sabhisharma-ise/Resume_website_mlsa_workshop#1]
![Screenshot 2023-04-04 at 00 29 51](https://user-images.githubusercontent.com/79051850/229602186-5fa316b8-9d42-44f9-9f94-4733403e07fd.jpg)
yaar yeh ... kya hota hai??
![Screenshot 2023-04-04 at 00 30 02](https://user-images.githubusercontent.com/79051850/229602191-12cb908f-d1cc-4a65-9105-83d0ada6ac69.jpg)
cool accomplishment kya hota hai?? thoda dhang seh likh loh
![Screenshot 2023-04-04 at 00 30 09](https://user-images.githubusercontent.com/79051850/229602194-6e3af612-e21c-4897-a99e-a644d13309e5.jpg)
email ka kabhi link nahi dehteh, email hamesha clearly visible hona chahiye

**Comment by sabhisharma-ise** [comment]
Ab check karo.
Sahi hai kya?

**Comment by tusharhqq** [comment]
Error mar rahi hai

**Comment by sabhisharma-ise** [comment]
Ab check Karo !

**Comment by tusharhqq** [comment]
Desktop ka toh pta nahi par mobile par toh, thoda line ki dikat ah Rahi hai

**Comment by sabhisharma-ise** [comment]
That's why i didn't kept the email and other whole links, as it was over-lapping in mobile. But i'll add a responsive code for mobile or maybe revert back to the previous one!

**Comment by tusharhqq** [comment]
Okay!
